services:
  pgdb:
    image: postgres:16.3-alpine
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - notesdb:/var/lib/postgresql/data

volumes:
  notesdb: