services:

  notes:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_docker
    ports:
      - 8000:8000
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - pgdb

  pgdb:
    image: postgres:16.3-alpine
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - notesdb:/var/lib/postgresql/data

volumes:
  notesdb: